config/routes.rb
Rails.application.routes.draw do

  get 'movies/' => 'movie#index', as: 'get_movies'
  # get 'movie/index'
  get 'movie/:imdb' => 'movie#index', as: 'get_movie'
  post 'movie/:imdb' => 'movie#add'
  delete 'movie/:imdb' => 'movie#delete', as: 'delete_movie'
  get 'search_genres/' => 'movie#search'

  get 'profile/index', to: 'profile#index', as: 'profile'
  delete 'profile/:imdb_id', to: 'profile#delete', as: 'delete'

  controller :error_pages do
    get :user_already_logged_in
    get :user_not_admin
    get :user_not_logged_in
  end
  # get 'error_pages/user_not_logged_in', to: 'error_pages#user_not_logged_in', as: 'user_not_logged_in'
  # get 'error_pages/user_not_admin', to: 'error_pages#user_not_admin', as: 'user_not_admin'
  # get 'error_pages/user_not_admin', to: 'error_pages#user_not_admin', as: 'user_not_admin'

  get 'session/logout', to: 'sessions#logout', as: 'logout_session'
  post 'session/create', to: 'sessions#create', as: 'create_session'

  get 'imdb_top250/:id' => 'imdb_top_250s#show'

  root 'pages#front_page'

  controller :pages do
    get :front_page
    get :filter_page
  end

  resources :imdb_top250s, only: [:index, :show]
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :imdb_id, uniqueness: true
  validates :imdb_id, presence: true
  validates :json, uniqueness: true
  validates :json, presence: true

  class << self
    def add_movie_if_not_exists(imdb_id, json)
      unless Movie.exists?(imdb_id: imdb_id)
        movie = Movie.new(imdb_id: imdb_id, json: json.to_json)
        movie.save
      end
    end
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  require 'http'

  def index
    respond_to do |format|
      if params[:imdb].nil?
        format.json { render :json => Movie.all }
      else
        format.html { @movie = get_json_from_id(params[:imdb]) }
        format.json { render :json => get_json_from_id(params[:imdb]).to_json }
      end
    end
  end

  def search
    filters = params[:filters].split(',')
    found_movies = []
    Movie.all.each do |movie|
      json = JSON.parse(movie['json'])
      genres = json['Genre'].split(',')
      genres.each do |genre|
        filters.each do |filter|
          if genre.strip.downcase == filter.strip.downcase
            found_movies.push(json)
          end
        end
      end
    end
    respond_to do |format|
      format.json { render :json => found_movies.uniq}
    end
  end

  # POST movie/:imdb
  def add
    if session[:username].nil?
      render :nothing => true, :status => 401
      return
    end
    json = get_json_from_id(params[:imdb])
    imdb_id = json['imdbID']

    saved_watchlist = Watchlist.add_movie_if_not_exists(session[:username], imdb_id)
    Movie.add_movie_if_not_exists(imdb_id, json)

    respond_to do |format|
      format.html { redirect_to front_page_path }
      format.json { render :json => {added: saved_watchlist} }
    end
  end

  def delete
    if session[:username].nil?
      render :nothing => true, :status => 401
      return
    end
    imdb_id = params[:imdb]
    respond_to do |format|
      if Watchlist.where(imdb_id: imdb_id, username: session[:username]).take.destroy!
        format.html { redirect_to front_page_path }
        format.json { render :json => {deleted: true} }
      else
        format.json { render :json => {deleted: false} }
      end
    end
  end

  def get_json_from_id(id)
    if Movie.exists?(imdb_id: id)
      json = Movie.find_by(imdb_id: id)['json']
      was_in_database = true
    else
      # Send a HTTP GET with IMDB ID to external movie API and receive the movie in JSON
      json = HTTP.get('http://www.omdbapi.com/', :params => {i: id, plot: 'full', apikey: 'ca17ed8a'})
      Movie.new(imdb_id: id, json: json).save
      was_in_database = false
    end
    response = JSON.parse(json)
    response['in_watchlist'] = Watchlist.is_movie_already_in_watchlist id
    response['movie_was_in_db'] = was_in_database
    response
  end

end

app/views/movie/index.html.erb
<!-- Prints movie details from movie_controller -->
<h1 id="title" class="title center-align"><%= @movie["Title"] + ' (' + @movie['Year'] + ')'%></h1>
<div id="movie" class="row">
    <div class="col m4">
      <img class="image" src="<%= @movie["Poster"] %>" alt="">
      <% if session[:username].nil? %>
          <p id="description">Please log in to add movie to your watchlist! </p>
          <p id="description"> Click <%= link_to 'here', new_user_path %> if you don't have a user yet!</p>
      <% else %>
          <% if @movie['in_watchlist'] %>
              <%= button_to '-', delete_movie_path,  method: :delete, params: {imdb: @movie["imdbID"]}, class: 'btn-floating btn-large waves-effect waves-light add-remove-button red' %>
          <%else%>
              <%= button_to '+', {:method => :post}, {class: 'btn-floating btn-large waves-effect waves-light add-remove-button green'} %>
          <% end %>
      <% end %>
    </div>

    <div class="col m8">
      <h4><i class="material-icons yellow-text">star_rate</i><%= @movie['imdbRating'] %>/10</h4>
      <h4>Duration: </h4><p id="description"><%= @movie['Runtime'] %></p>
      <h4>Genre: </h4><p id="description"><%= @movie['Genre'] %></p>
      <h4>Starring: </h4><p id="description"><%= @movie['Actors'] %></p>
      <h4>Plot: </h4><p id="description"><%= @movie['Plot'] %></p>
  </div>
</div>