config/routes.rb
Rails.application.routes.draw do

  get 'movies/' => 'movie#index', as: 'get_movies'
  # get 'movie/index'
  get 'movie/:imdb' => 'movie#index', as: 'get_movie'
  post 'movie/:imdb' => 'movie#add'
  delete 'movie/:imdb' => 'movie#delete', as: 'delete_movie'
  get 'search_genres/' => 'movie#search'

  get 'profile/index', to: 'profile#index', as: 'profile'
  delete 'profile/:imdb_id', to: 'profile#delete', as: 'delete'

  controller :error_pages do
    get :user_already_logged_in
    get :user_not_admin
    get :user_not_logged_in
  end
  # get 'error_pages/user_not_logged_in', to: 'error_pages#user_not_logged_in', as: 'user_not_logged_in'
  # get 'error_pages/user_not_admin', to: 'error_pages#user_not_admin', as: 'user_not_admin'
  # get 'error_pages/user_not_admin', to: 'error_pages#user_not_admin', as: 'user_not_admin'

  get 'session/logout', to: 'sessions#logout', as: 'logout_session'
  post 'session/create', to: 'sessions#create', as: 'create_session'

  get 'imdb_top250/:id' => 'imdb_top_250s#show'

  root 'pages#front_page'

  controller :pages do
    get :front_page
    get :filter_page
  end

  resources :imdb_top250s, only: [:index, :show]
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/error_pages_controller.rb
class ErrorPagesController < ApplicationController
  def user_not_logged_in
  end

  def user_not_admin
  end

  def user_already_logged_in
  end
end

app/views/error_pages/user_already_logged_in.html.erb
<h1 class="error-title">Already logged in</h1>
<p class="error-text">Click <%= link_to 'here', front_page_path %> to go back to the front page.</p>

app/views/error_pages/user_not_admin.html.erb
<h1 class="error-title">Not admin</h1>
<p class="error-text">In order to access this page you need admin-privileges, which you do not have.</p>
<p class="error-text">Click <%= link_to 'here', front_page_path %> to go back to the front page.</p>

app/views/error_pages/user_not_logged_in.html.erb
<h1 class="error-title">Not logged in</h1>
<p class="error-text">It seems you are not logged in. In order to access this page you you need to log in.</p>
<p class="error-text">If you have no account, you can click <%= link_to 'here', new_user_path %> to register new account.</p>
<p class="error-text">If you do not want to log in you can go <%= link_to 'here', front_page_path %> to back to the front page.