config/routes.rb
Rails.application.routes.draw do

  get 'movies/' => 'movie#index', as: 'get_movies'
  # get 'movie/index'
  get 'movie/:imdb' => 'movie#index', as: 'get_movie'
  post 'movie/:imdb' => 'movie#add'
  delete 'movie/:imdb' => 'movie#delete', as: 'delete_movie'
  get 'search_genres/' => 'movie#search'

  get 'profile/index', to: 'profile#index', as: 'profile'
  delete 'profile/:imdb_id', to: 'profile#delete', as: 'delete'

  controller :error_pages do
    get :user_already_logged_in
    get :user_not_admin
    get :user_not_logged_in
  end
  # get 'error_pages/user_not_logged_in', to: 'error_pages#user_not_logged_in', as: 'user_not_logged_in'
  # get 'error_pages/user_not_admin', to: 'error_pages#user_not_admin', as: 'user_not_admin'
  # get 'error_pages/user_not_admin', to: 'error_pages#user_not_admin', as: 'user_not_admin'

  get 'session/logout', to: 'sessions#logout', as: 'logout_session'
  post 'session/create', to: 'sessions#create', as: 'create_session'

  get 'imdb_top250/:id' => 'imdb_top_250s#show'

  root 'pages#front_page'

  controller :pages do
    get :front_page
    get :filter_page
  end

  resources :imdb_top250s, only: [:index, :show]
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/nav/_login.html.erb
<div id="login-modal" class="modal small">
  <div class="modal-content">

    <%= form_tag(create_session_path) do %>
        <fieldset>
          <legend>Login</legend>

          <div class="input-field col s12">
            <%= label_tag :name, 'Name:' %>
            <%= text_field_tag :name, params[:name] %>
          </div>

          <div class="input-field col s12">
            <%= label_tag :password, 'Password:' %>
            <%= password_field_tag :password, params[:password] %>
          </div>

          <div>
            <%= submit_tag "Login", {class: "modal-action modal-close waves-effect waves-light btn-flat"} %>
          </div>
        </fieldset>
        <%= link_to 'Click here to create a new account', new_user_path %>
    <% end %>

  </div>
</div>

app/views/nav/_logout.html.erb
<div id="logout-modal" class="modal small">
  <div class="modal-content">
    <%= link_to 'Logout', logout_session_path, {class: "modal-action modal-close waves-effect waves-light btn-flat"} %>
  </div>
</div>

app/views/nav/_nav.html.erb
<%= render 'nav/login' %>
<%= render 'nav/logout' %>
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <div id="brand">
        <%= link_to root_path, :class => 'brand-logo waves-effect waves-light' do %>
            <i class="material-icons md-36">movie</i>RMDB
        <% end %>
      </div>
      <div id="search-form" style="display: none;">
        <form>
          <div class="input-field">
            <input id="search" type="search" autocomplete="off">
            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
            <i class="material-icons">close</i>
          </div>
        </form>
      </div>
      <ul id="menu" class="right">
        <li id="toggle-search">
          <a class="waves-effect waves-light"><i class="material-icons">search</i></a>
        </li>
        <li>
          <%= link_to 'Profile', profile_path, {class: 'waves-effect waves-light'} %>
        </li>
        <li>
          <%= link_to 'Filter-page', filter_page_path, {class: 'waves-effect waves-light'} %>
        </li>
        <% if is_user_admin %>
            <li>
              <%= link_to 'Show-Users', users_path, {class: 'waves-effect waves-light'} %>
            </li>
        <% end %>
        <% if session[:username].nil? %>
            <li id="login">
              <a class="waves-effect waves-light"><i class="material-icons">person</i></a>
            </li>
        <% else %>
            <li id="logout">
              <a class="waves-effect waves-light">Logout</a>
            </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>